name: Build and Deploy Site with GitHub Actions

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: read
  id-token: write
  pages: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: '21'

    - name: Install Dependencies
      run: npm install

    - name: Build Static Files
      run: make

    - name: Upload Static Files as Artifact
      uses: actions/upload-pages-artifact@v1
      with:
        path: ./public

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'

    steps:
    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v1
