name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - master  # Or your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: '14' # Specify the node version your project requires

    - name: Install dependencies
      run: npm install

    - name: Run make
      run: make

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist # Make sure this matches the output directory of your build command in the Makefile
